import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: 'Chris Jones',
            email: 'user@example.com',
            birthDate: '03/1976',
            password: bcrypt.hashSync('user12345'),
            isAdmin: false,
            isManufacturer: false,
            isVendor: false
        },
        {
            name: 'Test Admin',
            email: 'admin@example.com',
            password: bcrypt.hashSync('adminUser12345'),
            isAdmin: true,
            isManufacturer: false,
            isVendor: false
        },
        {
            name: 'John Smith',
            email: 'manufacturer@example.com',
            phone: '(555) 555-5555',
            companyName: 'Thai Kratom',
            streetName: '119 Rural Road 3009',
            city: 'Song Phi Nong',
            province: 'Suphan Buri',
            postalCode: '72110',
            country: 'Thailand',
            password: bcrypt.hashSync('manUser12345'),
            isAdmin: false,
            isManufacturer: true,
            isVendor: false
        }
    ],
    categories: [
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder',
            categoryImage: '/images/do-raw-powder-bags.jpg',
            categoryText: 'Thailand was the point of origin for Kratom and a large part of Thailand\'s culture for over a century.  Kratom has been regarded as a culturally significant plant in Thai society since the 19th century, and in Thailand mythology Kratom is said to be the preffered food of dragons.  So try our dragon food from Thailand with Drangon Organics!'
        },
        {
            name: 'Extracts',
            slug: 'extracts',
            categoryImage: '/images/do-raw-powder-bags.jpg',
            categoryText: 'Thailand was the point of origin for Kratom and a large part of Thailand&apos;s culture for over a century.  Kratom has been regarded as a culturally significant plant in Thai society since the 19th century, and in Thailand mythology Kratom is said to be the preffered food of dragons.  So try our dragon food from Thailand with Drangon Organics!'
        }
    ],
    products: [
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-red-100g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-100g-pouch-raw-powder-red-front.jpg',
            imageTwo: '/images/do-100g-pouch-raw-powder-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'Red',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Gan Dang',
            size: '100g',
            price: 14.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: false
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-red-150g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-150g-pouch-raw-powder-red-front.jpg',
            imageTwo: '/images/do-150g-pouch-raw-powder-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'Red',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Gan Dang',
            size: '150g',
            price: 19.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: false
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-red-250g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-250g-pouch-raw-powder-red-front.jpg',
            imageTwo: '/images/do-250g-pouch-raw-powder-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'Red',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Gan Dang',
            size: '250g',
            price: 25.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: false
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-red-500g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-500g-pouch-raw-powder-red-front.jpg',
            imageTwo: '/images/do-500g-pouch-raw-powder-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'Red',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Kan Dang',
            size: '500g',
            price: 45.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
            description: 'Sample of a raw powder bag of red kratom',
            featured: true
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-green-100g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-100g-pouch-raw-powder-green-front.jpg',
            imageTwo: '/images/do-100g-pouch-raw-powder-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'Green',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Kan Dang',
            size: '100g',
            price: 14.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: false
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-green-150g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-150g-pouch-raw-powder-green-front.jpg',
            imageTwo: '/images/do-150g-pouch-raw-powder-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'Green',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Kan Dang',
            size: '150g',
            price: 19.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: false
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-green-250g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-250g-pouch-raw-powder-green-front.jpg',
            imageTwo: '/images/do-250g-pouch-raw-powder-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'Green',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Kan Dang',
            size: '250g',
            price: 25.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: false
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-green-500g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-500g-pouch-raw-powder-green-front.jpg',
            imageTwo: '/images/do-500g-pouch-raw-powder-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'Green',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Kan Dang',
            size: '500g',
            price: 45.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: true
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-white-100g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-100g-pouch-raw-powder-white-front.jpg',
            imageTwo: '/images/do-100g-pouch-raw-powder-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'White',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Kan Dang',
            size: '100g',
            price: 14.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: false
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-white-150g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-150g-pouch-raw-powder-white-front.jpg',
            imageTwo: '/images/do-150g-pouch-raw-powder-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'White',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Kan Dang',
            size: '150g',
            price: 19.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: false
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-white-250g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-250g-pouch-raw-powder-white-front.jpg',
            imageTwo: '/images/do-250g-pouch-raw-powder-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'White',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Kan Dang',
            size: '250g',
            price: 25.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: false
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-white-500g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-500g-pouch-raw-powder-white-front.jpg',
            imageTwo: '/images/do-500g-pouch-raw-powder-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'White',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Kan Dang',
            size: '500g',
            price: 45.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: true
        },
        {
            name: 'Gel Cap Extract',
            slug: 'gel-cap-extracts',
            category: 'extracts',
            imageOne: '/images/do-pill-bottle.jpg',
            imageTwo: '/images/do-pill-bottle.jpg',
            imageThree: '/images/do-red-leaf.jpg',
            imageFour: '/images/do-red-leaf.jpg',
            color: 'Red',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Gan Dang',
            size: '250g',
            price: 70,
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: true
        }
    ],
};

export default data;