const data = {
    categories: [
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder',
            categoryImage: '/images/do-raw-powder-bags.jpg',
            categoryText: 'Thailand was the point of origin for Kratom and a large part of Thailand\'s culture for over a century.  Kratom has been regarded as a culturally significant plant in Thai society since the 19th century, and in Thailand mythology Kratom is said to be the preffered food of dragons.  So try our dragon food from Thailand with Drangon Organics!'
        },
        {
            name: 'Extracts',
            slug: 'extracts',
            categoryImage: '/images/do-raw-powder-bags.jpg',
            categoryText: 'Thailand was the point of origin for Kratom and a large part of Thailand&apos;s culture for over a century.  Kratom has been regarded as a culturally significant plant in Thai society since the 19th century, and in Thailand mythology Kratom is said to be the preffered food of dragons.  So try our dragon food from Thailand with Drangon Organics!'
        }
    ],
    products: [
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-red-100g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-100g-raw-powder-red-front.jpg',
            imageTwo: '/images/do-100g-raw-powder-red-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'Red',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Gan Dang',
            size: '100g',
            price: 14.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: false
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-red-150g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-150g-raw-powder-red-front.jpg',
            imageTwo: '/images/do-150g-raw-powder-red-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'Red',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Gan Dang',
            size: '150g',
            price: 19.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: false
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-red-250g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-250g-raw-powder-red-front.jpg',
            imageTwo: '/images/do-250g-raw-powder-red-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'Red',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Gan Dang',
            size: '250g',
            price: 25.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: false
        },
        {
            name: 'Raw Leaf Powder',
            slug: 'raw-leaf-powder-red-500g',
            category: 'raw-leaf-powder',
            imageOne: '/images/do-500g-raw-powder-red-front.jpg',
            imageTwo: '/images/do-500g-raw-powder-red-back.jpg',
            imageThree: '/images/kratom-powder.jpg',
            imageFour: '/images/do-raw-powder-sample.jpg',
            color: 'Red',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Gan Dang',
            size: '500g',
            price: 45.99,
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Sample of a raw powder bag of red kratom',
            featured: true
        },
        {
            name: 'Berry Kratom Seltzer',
            slug: 'berry-seltzer',
            category: 'extracts',
            imageOne: '/images/do-seltzer-berry.jpg',
            imageTwo: '/images/do-seltzer-berry.jpg',
            imageThree: '/images/do-red-leaf.jpg',
            imageFour: '/images/do-red-leaf.jpg',
            color: 'Red',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Gan Dang',
            size: '250g',
            price: 70,
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            featured: true
        },
        {
            name: 'Lemon Kratom Seltzer',
            slug: 'lemon-seltzer',
            category: 'extracts',
            imageOne: '/images/do-seltzer-berry.jpg',
            imageTwo: '/images/do-seltzer-berry.jpg',
            imageThree: '/images/do-red-leaf.jpg',
            imageFour: '/images/do-red-leaf.jpg',
            color: 'Red',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Gan Dang',
            size: '250g',
            price: 70,
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Sample of a raw powder bag of red kratom',
            featured: false
        },
        {
            name: 'Cherry Kratom Seltzer',
            slug: 'cherry-seltzer',
            category: 'extracts',
            imageOne: '/images/do-seltzer-berry.jpg',
            imageTwo: '/images/do-seltzer-berry.jpg',
            imageThree: '/images/do-red-leaf.jpg',
            imageFour: '/images/do-red-leaf.jpg',
            color: 'Red',
            region: 'Chumphon Thailand',
            leafType: 'Traditional Leaf',
            leafName: 'Gan Dang',
            size: '250g',
            price: 70,
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Sample of a raw powder bag of red kratom',
            featured: false
        },
    ],
};

export default data;